### ISSUE TITLE
Exception while creating FTLFrame

### ISSUE THREAD

**Issue by EnkerDraco** [ComaToes/ftl-profile-editor#7]
2:47:20.463 [main] ERROR net.blerf.ftl.FTLProfileEditor - Exception while creating FTLFrame java.lang.NullPointerException
    at com.sun.java.swing.plaf.windows.XPStyle.getTypeEnumName(Unknown Source)
    at com.sun.java.swing.plaf.windows.XPStyle.getBorder(Unknown Source)
    at com.sun.java.swing.plaf.windows.WindowsLookAndFeel$XPBorderValue.getXPValue(Unknown Source)
    at com.sun.java.swing.plaf.windows.WindowsLookAndFeel$XPValue.createValue(Unknown Source)
    at javax.swing.UIDefaults.getFromHashtable(Unknown Source)
    at javax.swing.UIDefaults.get(Unknown Source)
    at javax.swing.MultiUIDefaults.get(Unknown Source)
    at javax.swing.UIDefaults.getBorder(Unknown Source)
    at javax.swing.UIManager.getBorder(Unknown Source)
    at javax.swing.border.TitledBorder.getBorder(Unknown Source)
    at javax.swing.border.TitledBorder.getBorderInsets(Unknown Source)
    at javax.swing.border.TitledBorder.getBorderInsets(Unknown Source)
    at javax.swing.JComponent.getInsets(Unknown Source)
    at java.awt.GridLayout.minimumLayoutSize(Unknown Source)
    at java.awt.Container.minimumSize(Unknown Source)
    at java.awt.Container.getMinimumSize(Unknown Source)
    at javax.swing.JComponent.getMinimumSize(Unknown Source)
    at javax.swing.BoxLayout.checkRequests(Unknown Source)
    at javax.swing.BoxLayout.preferredLayoutSize(Unknown Source)
    at java.awt.Container.preferredSize(Unknown Source)
    at java.awt.Container.getPreferredSize(Unknown Source)
    at javax.swing.JComponent.getPreferredSize(Unknown Source)
    at javax.swing.ScrollPaneLayout.layoutContainer(Unknown Source)
    at java.awt.Container.layout(Unknown Source)
    at java.awt.Container.doLayout(Unknown Source)
    at java.awt.Container.validateTree(Unknown Source)
    at java.awt.Container.validateTree(Unknown Source)
    at java.awt.Container.validateTree(Unknown Source)
    at java.awt.Container.validateTree(Unknown Source)
    at java.awt.Container.validateTree(Unknown Source)
    at java.awt.Container.validateTree(Unknown Source)
    at java.awt.Container.validate(Unknown Source)
    at java.awt.Window.show(Unknown Source)
    at java.awt.Component.show(Unknown Source)
    at java.awt.Component.setVisible(Unknown Source)
    at java.awt.Window.setVisible(Unknown Source)
    at net.blerf.ftl.FTLProfileEditor.main(FTLProfileEditor.java:19)

**Comment by Vhati** [comment]
That's a weird one.
It may be a bug in Java itself, so updating that would be worth trying.
I proposed a change for the next version of the editor that _might_ fix it.

**Comment by ComaToes** [comment]
This is a Java bug when you are using a custom Windows theme. Switching to the default theme should fix it. The next release (v11) should allow you to work around this bug by editing/creating ftl-editor.cfg in the same folder as the .jar and adding a line "useDefaultUI=true".
